"use client"

import { useState } from "react"
import { FileText, Download, Loader2, AlertCircle, Stethoscope } from "lucide-react"

export function PractitionerReportCard() {
  const [status, setStatus] = useState<"idle" | "generating" | "ready" | "error">("idle")
  const [reportContent, setReportContent] = useState<string | null>(null)
  const [reportName, setReportName] = useState<string>("")
  const [errorMsg, setErrorMsg] = useState<string>("")

  async function handleGenerate() {
    setStatus("generating")
    setErrorMsg("")

    try {
      const res = await fetch("/api/doctor-report/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      })

      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        if (res.status === 403) {
          setErrorMsg("This feature is available on the Transform plan.")
        } else if (res.status === 400) {
          setErrorMsg("Complete your gut health assessment first to generate a report.")
        } else {
          setErrorMsg(data.error ?? "Something went wrong. Please try again.")
        }
        setStatus("error")
        return
      }

      const data = await res.json()
      setReportContent(data.content)
      setReportName(data.name ?? "EatoBiotics Report")
      setStatus("ready")
    } catch {
      setErrorMsg("Network error. Please check your connection and try again.")
      setStatus("error")
    }
  }

  function handleDownload() {
    if (!reportContent) return

    const date = new Date().toLocaleDateString("en-IE", {
      day: "numeric",
      month: "long",
      year: "numeric",
    })

    const fullReport = `EatoBiotics — Practitioner Report
Generated: ${date}
Name: ${reportName}

${reportContent}

---
This report was generated by EatoBiotics (eatobiotics.com).
It is intended to support a conversation with a qualified healthcare practitioner
and does not constitute medical advice or diagnosis.`

    const blob = new Blob([fullReport], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `EatoBiotics-Practitioner-Report-${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="rounded-2xl border border-border bg-card overflow-hidden">
      {/* Top accent */}
      <div
        className="h-1 w-full"
        style={{ background: "linear-gradient(90deg, var(--icon-teal), var(--icon-green))" }}
      />

      <div className="p-6">
        <div className="flex items-start gap-3 mb-4">
          <div
            className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl"
            style={{ background: "linear-gradient(135deg, var(--icon-teal), var(--icon-green))" }}
          >
            <Stethoscope size={18} className="text-white" />
          </div>
          <div>
            <h3 className="font-serif text-base font-semibold text-foreground">
              Share with your practitioner
            </h3>
            <p className="mt-0.5 text-xs text-muted-foreground">
              Transform plan · One-page summary
            </p>
          </div>
        </div>

        <p className="text-sm leading-relaxed text-muted-foreground mb-5">
          A one-page summary of your gut health score, 5-pillar breakdown, and top food
          recommendations — designed to start a conversation with your doctor or nutritionist,
          not replace one.
        </p>

        {status === "idle" && (
          <button
            onClick={handleGenerate}
            className="brand-gradient flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90"
          >
            <FileText size={15} />
            Generate Report
          </button>
        )}

        {status === "generating" && (
          <div className="flex items-center justify-center gap-2 rounded-xl border border-border bg-secondary/20 py-3">
            <Loader2 size={15} className="animate-spin text-muted-foreground" />
            <span className="text-sm text-muted-foreground">Generating your report…</span>
          </div>
        )}

        {status === "ready" && (
          <div className="space-y-3">
            <div
              className="rounded-xl border p-4"
              style={{
                borderColor: "color-mix(in srgb, var(--icon-green) 30%, transparent)",
                background: "color-mix(in srgb, var(--icon-green) 5%, transparent)",
              }}
            >
              <p className="text-xs font-bold uppercase tracking-widest text-[var(--icon-green)] mb-1">
                ✓ Report ready
              </p>
              <p className="text-sm text-foreground/80 line-clamp-3">{reportContent}</p>
            </div>
            <button
              onClick={handleDownload}
              className="flex w-full items-center justify-center gap-2 rounded-xl border-2 border-icon-teal py-3 text-sm font-semibold text-foreground transition-colors hover:bg-icon-teal hover:text-white"
            >
              <Download size={15} />
              Download Report
            </button>
            <button
              onClick={() => { setStatus("idle"); setReportContent(null) }}
              className="w-full text-xs text-muted-foreground/60 hover:text-muted-foreground transition-colors"
            >
              Generate again
            </button>
          </div>
        )}

        {status === "error" && (
          <div className="space-y-3">
            <div className="flex items-start gap-2 rounded-xl border border-destructive/20 bg-destructive/5 p-4">
              <AlertCircle size={15} className="mt-0.5 shrink-0 text-destructive" />
              <p className="text-sm text-destructive">{errorMsg}</p>
            </div>
            <button
              onClick={() => setStatus("idle")}
              className="w-full rounded-xl border border-border py-2.5 text-sm font-medium text-muted-foreground transition-colors hover:bg-secondary/40 hover:text-foreground"
            >
              Try again
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
