import type { AddonType } from "@/lib/addon-types"
import type { DeepQuestion } from "@/lib/deep-assessment"

/**
 * The lens questions — the few extra questions a purchased add-on adds to the
 * deep assessment.
 *
 * ── Why this is a deterministic bank ─────────────────────────────────────────
 *
 * The core deep questions are generated by Claude (app/api/generate-deep-questions),
 * which is right for them: they probe the WHY behind a particular score profile
 * and benefit from variation. The lens questions are the opposite job. The
 * report has to interpret them, so the interpreter needs to know what it is
 * reading — a fixed set of ids and answer values it can branch on. A generated
 * lens question would give the fallback builder nothing reliable to key off,
 * and "every add-on changes the question set" could then only be asserted as
 * shape rather than content, and only when an API key is present.
 *
 * ── Scope ────────────────────────────────────────────────────────────────────
 *
 * Four to five questions each. This is a lens on the foundation assessment, not
 * a second assessment: the standalone Stability, Glucose, Mind and Performance
 * assessments still exist at their own routes and go far deeper. These ask only
 * what the lens chapter needs in order to say something specific.
 *
 * ── Rules these questions obey ───────────────────────────────────────────────
 *
 *  1. Non-diagnostic and non-judgemental. They ask what someone NOTICES, never
 *     what they have. No symptom checklist that reads as a screening tool.
 *  2. No medical measurement the product cannot verify — no HbA1c, no fasting
 *     glucose, no blood pressure, no diagnoses, no medication names, no weight
 *     targets. Glucose in particular asks about observed energy and craving
 *     PATTERNS, because this questionnaire does not measure blood glucose and
 *     must not imply that it does. `tests/unit/addon-questions.test.ts` greps
 *     the banks for those terms.
 *  3. Answer options are stable `value` strings. The lens builder branches on
 *     them, so renaming a value is a breaking change to report content.
 *  4. Family wording where the personal phrasing would not fit a household.
 *
 * The `intent` / `answerField` / `whyNeeded` metadata on every spec is not
 * decoration: it is what the review pack is generated from, so the
 * documentation cannot drift away from the questions it describes.
 */

export interface AddonQuestionSpec {
  /** Stable id. `lens<n>` — never `dq<n>`, which is the core generated set. */
  id: string
  type: DeepQuestion["type"]
  /** Which pathway this question informs, for the existing DeepPillar typing. */
  pillar: DeepQuestion["pillar"]
  text: string
  /** Household phrasing. Omitted when the personal wording already fits. */
  familyText?: string
  eduContext?: string
  familyEduContext?: string
  options?: Array<{ label: string; value: string }>
  min?: number
  max?: number
  minLabel?: string
  maxLabel?: string
  required: boolean

  /* ── Documentation, carried as data ── */
  /** What this question is intended to support in the report. */
  intent: string
  /** The field of the lens chapter its answer feeds. */
  answerField: string
  /** Why the lens cannot say something useful without it. */
  whyNeeded: string
}

const FREQ5 = [
  { label: "Rarely or never", value: "rarely" },
  { label: "About once a week", value: "weekly" },
  { label: "A few times a week", value: "often" },
  { label: "Most days", value: "daily" },
  { label: "I'm not sure", value: "unsure" },
]

/* ── Stability ──────────────────────────────────────────────────────────────
 * Concepts reused from the standalone assessment in lib/stability/questions.ts
 * — predictability, urgency, post-meal timing — reduced to the four the lens
 * chapter actually reads. */
const STABILITY: AddonQuestionSpec[] = [
  {
    id: "lens1",
    type: "single",
    pillar: "consistency",
    text: "How predictable is your digestion from day to day?",
    familyText: "How predictable is digestion across your household from day to day?",
    eduContext: "Rhythm is often easier to change than any single food, so it is a useful place to start.",
    options: [
      { label: "Very predictable — much the same each day", value: "predictable" },
      { label: "Mostly predictable, with occasional off days", value: "mostly" },
      { label: "Unpredictable — it varies a lot", value: "unpredictable" },
      { label: "I haven't paid attention to this", value: "unsure" },
    ],
    required: true,
    intent: "Sets whether the lens leads on protecting an existing rhythm or building one.",
    answerField: "patternSummary, priorityConnection",
    whyNeeded: "Without it the chapter cannot tell a steady system from an erratic one, and would give both the same advice.",
  },
  {
    id: "lens2",
    type: "single",
    pillar: "feeling",
    text: "When digestive discomfort shows up, when does it usually happen?",
    familyText: "When digestive discomfort shows up in your household, when does it usually happen?",
    eduContext: "Timing is a pattern clue — it points at meals, rhythm or rest rather than at any one food.",
    options: [
      { label: "Soon after eating", value: "after-meals" },
      { label: "Later in the day or evening", value: "later" },
      { label: "On busy or stressful days", value: "stress-linked" },
      { label: "No clear pattern", value: "no-pattern" },
      { label: "It doesn't really show up", value: "none" },
    ],
    required: true,
    intent: "Chooses which observable signals the chapter asks the reader to watch.",
    answerField: "signals",
    whyNeeded: "Post-meal, evening and stress-linked patterns each point at a different practical change.",
  },
  {
    id: "lens3",
    type: "multi",
    pillar: "prebiotics",
    text: "Which of these are already a regular part of your week?",
    familyText: "Which of these are already a regular part of your household's week?",
    eduContext: "Fibre variety and fermented foods act on different parts of the same system.",
    options: [
      { label: "A range of different vegetables", value: "veg-variety" },
      { label: "Beans, lentils or other legumes", value: "legumes" },
      { label: "Whole grains such as oats or brown rice", value: "wholegrains" },
      { label: "Fermented foods such as yoghurt, kefir or kimchi", value: "fermented" },
      { label: "None of these regularly", value: "none" },
    ],
    required: true,
    intent: "Grounds the lens actions in what is already working rather than starting from nothing.",
    answerField: "pathwayConnections, loopAdditions",
    whyNeeded: "Recommending fermented foods to someone already eating them daily wastes the one action they will read.",
  },
  {
    id: "lens4",
    type: "single",
    pillar: "postbiotics",
    text: "How often do meals happen at roughly the same times?",
    familyText: "How often do household meals happen at roughly the same times?",
    eduContext: "Regular timing gives gut microbes a predictable schedule.",
    options: FREQ5,
    required: true,
    intent: "Decides whether a rhythm action belongs in the 30-day loop.",
    answerField: "loopAdditions",
    whyNeeded: "Meal timing is the lever most often available when food variety is already good.",
  },
]

/* ── Glucose ────────────────────────────────────────────────────────────────
 * Deliberately pattern-based. This questionnaire does not measure blood
 * glucose, so it asks only about what someone notices — energy, cravings,
 * timing — and never for a reading, a diagnosis or a medication. */
const GLUCOSE: AddonQuestionSpec[] = [
  {
    id: "lens1",
    type: "single",
    pillar: "feeling",
    text: "How does your energy usually behave in the two hours after a main meal?",
    familyText: "How does energy usually behave across your household in the two hours after a main meal?",
    eduContext: "What you notice after eating is a pattern clue, not a measurement.",
    options: [
      { label: "Steady — much the same as before", value: "steady" },
      { label: "A noticeable dip", value: "dip" },
      { label: "A lift, then a dip", value: "lift-then-dip" },
      { label: "It varies with the meal", value: "varies" },
      { label: "I haven't noticed", value: "unsure" },
    ],
    required: true,
    intent: "Sets the lens's central observation and whether it leads on meal composition or rhythm.",
    answerField: "patternSummary, priorityConnection",
    whyNeeded: "A steady pattern and a crash pattern deserve opposite framing — protect versus adjust.",
  },
  {
    id: "lens2",
    type: "single",
    pillar: "feeding",
    text: "What does a typical breakfast look like on a workday?",
    familyText: "What does a typical household breakfast look like on a school or workday?",
    eduContext: "Breakfast tends to set the shape of the day, and it is usually the most repeatable meal.",
    options: [
      { label: "Mostly carbohydrate — toast, cereal, pastry", value: "carb-led" },
      { label: "Carbohydrate with some protein or fat", value: "mixed" },
      { label: "Protein-led — eggs, yoghurt, fish", value: "protein-led" },
      { label: "I usually skip it", value: "skipped" },
    ],
    required: true,
    intent: "Gives the loop action something concrete and repeatable to attach to.",
    answerField: "loopAdditions",
    whyNeeded: "Generic 'balance your meals' advice is unusable; the action has to name the meal they actually eat.",
  },
  {
    id: "lens3",
    type: "single",
    pillar: "feeling",
    text: "When do cravings for something sweet most often turn up?",
    familyText: "When do cravings for something sweet most often turn up in your household?",
    eduContext: "Craving timing often tracks meal spacing rather than willpower.",
    options: [
      { label: "Mid-morning", value: "mid-morning" },
      { label: "Mid-afternoon", value: "mid-afternoon" },
      { label: "Evening", value: "evening" },
      { label: "Not really a pattern", value: "no-pattern" },
    ],
    required: true,
    intent: "Selects which observation prompt the chapter offers.",
    answerField: "signals",
    whyNeeded: "The prompt has to point at a time of day the reader can actually watch.",
  },
  {
    id: "lens4",
    type: "multi",
    pillar: "prebiotics",
    text: "Which of these usually appear alongside your carbohydrates?",
    familyText: "Which of these usually appear alongside carbohydrates at household meals?",
    eduContext: "Fibre, protein and fat alongside a carbohydrate change how a meal is experienced.",
    options: [
      { label: "Vegetables or salad", value: "veg" },
      { label: "A protein — eggs, fish, meat, tofu, pulses", value: "protein" },
      { label: "Healthy fats — olive oil, nuts, avocado", value: "fats" },
      { label: "Usually the carbohydrate on its own", value: "alone" },
    ],
    required: true,
    intent: "Connects the lens to the Prebiotics pathway and shapes the practical action.",
    answerField: "pathwayConnections, loopAdditions",
    whyNeeded: "Meal composition is the change most within reach, and the answer says which part is missing.",
  },
]

/* ── Mind ───────────────────────────────────────────────────────────────────
 * Non-diagnostic by construction. No question asks about anxiety, depression,
 * diagnosis, medication or clinical sleep disorder — only about everyday
 * routine and what the reader notices. */
const MIND: AddonQuestionSpec[] = [
  {
    id: "lens1",
    type: "single",
    pillar: "consistency",
    text: "How steady is your eating rhythm on a busy day?",
    familyText: "How steady is your household's eating rhythm on a busy day?",
    eduContext: "Busy days tend to reveal which habits are genuinely established.",
    options: [
      { label: "Much the same as a calm day", value: "steady" },
      { label: "Meals get later, but still happen", value: "delayed" },
      { label: "Meals get skipped or replaced by snacks", value: "skipped" },
      { label: "It varies a lot", value: "varies" },
    ],
    required: true,
    intent: "Sets whether the lens leads on protecting rhythm or rebuilding it.",
    answerField: "patternSummary, priorityConnection",
    whyNeeded: "Rhythm under pressure is the part of the pattern most connected to how food and focus interact.",
  },
  {
    id: "lens2",
    type: "single",
    pillar: "feeling",
    text: "When during the day do you most often notice your focus dropping?",
    familyText: "When during the day is focus most often hardest in your household?",
    eduContext: "Noticing when, rather than why, is the useful first step.",
    options: [
      { label: "Mid-morning", value: "mid-morning" },
      { label: "Early afternoon", value: "early-afternoon" },
      { label: "Late afternoon or evening", value: "late" },
      { label: "No consistent time", value: "no-pattern" },
    ],
    required: true,
    intent: "Chooses the observation prompt and which meal the loop action attaches to.",
    answerField: "signals, loopAdditions",
    whyNeeded: "An observation prompt with no time attached is not something anyone can act on.",
  },
  {
    id: "lens3",
    type: "multi",
    pillar: "probiotics",
    text: "Which of these show up in a typical week?",
    familyText: "Which of these show up in a typical household week?",
    eduContext: "Fermented foods, oily fish and colourful plants are each studied in relation to the gut–brain axis.",
    options: [
      { label: "Fermented foods — yoghurt, kefir, kimchi, sauerkraut", value: "fermented" },
      { label: "Oily fish such as salmon, mackerel or sardines", value: "oily-fish" },
      { label: "Nuts, seeds or olive oil", value: "nuts-oils" },
      { label: "A wide range of colourful plants", value: "colour" },
      { label: "None of these regularly", value: "none" },
    ],
    required: true,
    intent: "Links the lens to the pathway scores and grounds its actions.",
    answerField: "pathwayConnections, loopAdditions",
    whyNeeded: "Without it the chapter cannot tell whether the useful move is adding or protecting.",
  },
  {
    id: "lens4",
    type: "single",
    pillar: "postbiotics",
    text: "How often does the last meal of the day land close to bedtime?",
    familyText: "How often does the household's last meal land close to bedtime?",
    eduContext: "Late eating is associated with lighter, more broken rest for some people.",
    options: FREQ5,
    required: true,
    intent: "Adds a rhythm action to the loop where one is warranted.",
    answerField: "loopAdditions",
    whyNeeded: "Meal timing is a food-side lever the report can legitimately discuss; sleep quality itself is not something it may claim to change.",
  },
]

/* ── Performance ────────────────────────────────────────────────────────────
 * Everyday capacity, not athletic prescription. No training-load targets, no
 * body-composition goals, no promises about output. */
const PERFORMANCE: AddonQuestionSpec[] = [
  {
    id: "lens1",
    type: "single",
    pillar: "consistency",
    text: "How does eating usually fit around the active parts of your day?",
    familyText: "How does eating usually fit around the active parts of your household's day?",
    eduContext: "Fuelling around activity is mostly a timing question, not a supplement one.",
    options: [
      { label: "I eat before, and again afterwards", value: "both" },
      { label: "Usually only afterwards", value: "after-only" },
      { label: "Usually only beforehand", value: "before-only" },
      { label: "Often neither — I fit it in when I can", value: "neither" },
    ],
    required: true,
    intent: "Sets the lens's central pattern and the shape of its actions.",
    answerField: "patternSummary, loopAdditions",
    whyNeeded: "Someone already fuelling on both sides needs protection advice, not a new routine.",
  },
  {
    id: "lens2",
    type: "single",
    pillar: "feeling",
    text: "How do you usually feel the day after a demanding day?",
    familyText: "How does your household usually feel the day after a demanding day?",
    eduContext: "Recovery is a pattern worth noticing over weeks rather than judging in a single day.",
    options: [
      { label: "Back to normal", value: "recovered" },
      { label: "A bit flat, but functional", value: "flat" },
      { label: "Noticeably depleted", value: "depleted" },
      { label: "It varies a lot", value: "varies" },
    ],
    required: true,
    intent: "Chooses which signals the chapter asks the reader to watch.",
    answerField: "signals, priorityConnection",
    whyNeeded: "Recovery is the observation that makes the rest of the chapter concrete.",
  },
  {
    id: "lens3",
    type: "multi",
    pillar: "prebiotics",
    text: "Which of these are usually part of your main meals?",
    familyText: "Which of these are usually part of your household's main meals?",
    eduContext: "Protein, colour and slow carbohydrates each do a different job in the same meal.",
    options: [
      { label: "A clear protein source", value: "protein" },
      { label: "Colourful vegetables or fruit", value: "colour" },
      { label: "Slow carbohydrates — oats, whole grains, potatoes", value: "slow-carbs" },
      { label: "Healthy fats — olive oil, nuts, avocado", value: "fats" },
      { label: "It depends entirely on the day", value: "variable" },
    ],
    required: true,
    intent: "Connects the lens to the pathway scores and names the missing component.",
    answerField: "pathwayConnections, loopAdditions",
    whyNeeded: "The action has to name what is absent from their plate, not describe an ideal one.",
  },
  {
    id: "lens4",
    type: "single",
    pillar: "postbiotics",
    text: "How consistent is your sleep and wind-down routine across a week?",
    familyText: "How consistent is your household's sleep and wind-down routine across a week?",
    eduContext: "Recovery depends on rest as much as on food, and rhythm is the part food can support.",
    options: FREQ5,
    required: true,
    intent: "Adds a recovery-rhythm action to the loop where one is warranted.",
    answerField: "loopAdditions",
    whyNeeded: "Without it the lens can only talk about food, which is half of what recovery actually depends on.",
  },
]

export const ADDON_QUESTIONS: Record<AddonType, AddonQuestionSpec[]> = {
  stability: STABILITY,
  glucose: GLUCOSE,
  mind: MIND,
  performance: PERFORMANCE,
}

/**
 * The lens questions for a purchased add-on, in `DeepQuestion` shape.
 *
 * Returns `[]` for `null` — the no-add-on questionnaire is then byte-identical
 * to what it was before this existed, which is the property
 * `tests/unit/addon-questions.test.ts` pins.
 */
export function addonQuestionsFor(
  addon: AddonType | null | undefined,
  foundation: "you" | "family" = "you",
): DeepQuestion[] {
  if (!addon) return []
  const specs = ADDON_QUESTIONS[addon]
  if (!specs) return []

  const family = foundation === "family"

  return specs.map((spec) => ({
    id: spec.id,
    type: spec.type,
    pillar: spec.pillar,
    section: "lens" as const,
    text: family && spec.familyText ? spec.familyText : spec.text,
    eduContext: family && spec.familyEduContext ? spec.familyEduContext : spec.eduContext,
    ...(spec.options ? { options: spec.options } : {}),
    ...(spec.min !== undefined ? { min: spec.min } : {}),
    ...(spec.max !== undefined ? { max: spec.max } : {}),
    ...(spec.minLabel ? { minLabel: spec.minLabel } : {}),
    ...(spec.maxLabel ? { maxLabel: spec.maxLabel } : {}),
    required: spec.required,
  }))
}

/** The lens answers only, keyed by question id — what the lens builder reads. */
export function lensAnswers(
  addon: AddonType | null | undefined,
  answers: Record<string, unknown>,
): Record<string, unknown> {
  if (!addon) return {}
  const ids = new Set(ADDON_QUESTIONS[addon]?.map((q) => q.id) ?? [])
  return Object.fromEntries(Object.entries(answers).filter(([k]) => ids.has(k)))
}
