import type { Chapter } from "./chapters"
import { PART_COLORS } from "./chapters"

export { PART_COLORS }

export const chaptersFamily: Chapter[] = [
  // ── PART I ──────────────────────────────────────────────────────────────────
  {
    number: 1,
    slug: "chapter-1",
    part: "I",
    partTitle: "The Family Food System",
    title: "The Food System Inside Your Family",
    description: "How the home shapes lifelong health, food identity, and habits.",
    status: "coming-soon",
    readingTime: 24,
  },
  {
    number: 2,
    slug: "chapter-2",
    part: "I",
    partTitle: "The Family Food System",
    title: "Modern Family Life Broke the System",
    description: "Busy schedules, convenience food, screens, fragmented mealtimes, stress, and disconnection.",
    status: "coming-soon",
    readingTime: 28,
  },
  {
    number: 3,
    slug: "chapter-3",
    part: "I",
    partTitle: "The Family Food System",
    title: "The Family Biotics Framework",
    description: "How microbiome support works across parents, children, and shared meals.",
    status: "coming-soon",
    readingTime: 26,
  },
  {
    number: 4,
    slug: "chapter-4",
    part: "I",
    partTitle: "The Family Food System",
    title: "The EatoBiotics Family Method",
    description: "Simple household rules, rhythms, and repeatable systems.",
    status: "coming-soon",
    readingTime: 30,
  },

  // ── PART II ─────────────────────────────────────────────────────────────────
  {
    number: 5,
    slug: "chapter-5",
    part: "II",
    partTitle: "The Family Foods",
    title: "Building a Microbiome-Friendly Family Kitchen",
    description: "What to stock, what to remove, what to normalize.",
    status: "coming-soon",
    readingTime: 38,
  },
  {
    number: 6,
    slug: "chapter-6",
    part: "II",
    partTitle: "The Family Foods",
    title: "Family Prebiotic Foods",
    description: "Affordable, practical, child-friendly fiber-first foods.",
    status: "coming-soon",
    readingTime: 40,
  },
  {
    number: 7,
    slug: "chapter-7",
    part: "II",
    partTitle: "The Family Foods",
    title: "Family Probiotic Foods",
    description: "How to introduce fermented foods in realistic ways.",
    status: "coming-soon",
    readingTime: 38,
  },
  {
    number: 8,
    slug: "chapter-8",
    part: "II",
    partTitle: "The Family Foods",
    title: "Family Postbiotic Results",
    description: "What stronger daily inputs may support across the household.",
    status: "coming-soon",
    readingTime: 35,
  },
  {
    number: 9,
    slug: "chapter-9",
    part: "II",
    partTitle: "The Family Foods",
    title: "The Family Plate",
    description: "How to build meals that work for adults and children together.",
    status: "coming-soon",
    readingTime: 42,
  },

  // ── PART III ────────────────────────────────────────────────────────────────
  {
    number: 10,
    slug: "chapter-10",
    part: "III",
    partTitle: "The 5 Family Outcomes",
    title: "Better Digestion at Home",
    description: "Common digestive issues, tolerance, routine, and food quality.",
    status: "coming-soon",
    readingTime: 44,
  },
  {
    number: 11,
    slug: "chapter-11",
    part: "III",
    partTitle: "The 5 Family Outcomes",
    title: "Family Immunity",
    description: "Shared resilience, seasonal protection, and the household environment.",
    status: "coming-soon",
    readingTime: 48,
  },
  {
    number: 12,
    slug: "chapter-12",
    part: "III",
    partTitle: "The 5 Family Outcomes",
    title: "Stable Energy & Appetite",
    description: "Reducing sugar crashes, grazing, and chaotic eating.",
    status: "coming-soon",
    readingTime: 46,
  },
  {
    number: 13,
    slug: "chapter-13",
    part: "III",
    partTitle: "The 5 Family Outcomes",
    title: "Mood, Behaviour & Emotional Regulation",
    description: "How food rhythms may influence mood, focus, and family calm.",
    status: "coming-soon",
    readingTime: 50,
  },
  {
    number: 14,
    slug: "chapter-14",
    part: "III",
    partTitle: "The 5 Family Outcomes",
    title: "Growth, Recovery & Development",
    description: "Nutrition for children, parents, stress recovery, and sleep support.",
    status: "coming-soon",
    readingTime: 52,
  },

  // ── PART IV ─────────────────────────────────────────────────────────────────
  {
    number: 15,
    slug: "chapter-15",
    part: "IV",
    partTitle: "The Practical Family System",
    title: "The Family Kitchen System",
    description: "Shopping, prep, leftovers, batch cooking, routines.",
    status: "coming-soon",
    readingTime: 55,
  },
  {
    number: 16,
    slug: "chapter-16",
    part: "IV",
    partTitle: "The Practical Family System",
    title: "Breakfast, Lunch, Dinner, Snacks",
    description: "How to structure a realistic food week.",
    status: "coming-soon",
    readingTime: 58,
  },
  {
    number: 17,
    slug: "chapter-17",
    part: "IV",
    partTitle: "The Practical Family System",
    title: "The 7-Day Family Reset",
    description: "A simple reset after holidays, sickness, stress, or drift.",
    status: "coming-soon",
    readingTime: 50,
  },
  {
    number: 18,
    slug: "chapter-18",
    part: "IV",
    partTitle: "The Practical Family System",
    title: "The 21-Day Family Build",
    description: "A deeper household habit-building plan.",
    status: "coming-soon",
    readingTime: 55,
  },
  {
    number: 19,
    slug: "chapter-19",
    part: "IV",
    partTitle: "The Practical Family System",
    title: "The Family Food Index",
    description: "How to assess foods by nutrition, microbiome support, ease, acceptance, and cost.",
    status: "coming-soon",
    readingTime: 48,
  },

  // ── PART V ──────────────────────────────────────────────────────────────────
  {
    number: 20,
    slug: "chapter-20",
    part: "V",
    partTitle: "Real Family Life",
    title: "School, Work, Sports, and Busy Days",
    description: "How to stay consistent in normal life.",
    status: "coming-soon",
    readingTime: 52,
  },
  {
    number: 21,
    slug: "chapter-21",
    part: "V",
    partTitle: "Real Family Life",
    title: "Picky Eating, Resistance, and Food Transitions",
    description: "How to support change without conflict.",
    status: "coming-soon",
    readingTime: 48,
  },
  {
    number: 22,
    slug: "chapter-22",
    part: "V",
    partTitle: "Real Family Life",
    title: "Eating Together",
    description: "The power of meals, modeling, and family rituals.",
    status: "coming-soon",
    readingTime: 45,
  },
  {
    number: 23,
    slug: "chapter-23",
    part: "V",
    partTitle: "Real Family Life",
    title: "Movement, Outdoors, and Play",
    description: "How movement supports digestion, mood, and development.",
    status: "coming-soon",
    readingTime: 42,
  },
  {
    number: 24,
    slug: "chapter-24",
    part: "V",
    partTitle: "Real Family Life",
    title: "Calm, Sleep, and the Home Nervous System",
    description: "Evening rhythm, screens, stress, rest, and recovery.",
    status: "coming-soon",
    readingTime: 46,
  },

  // ── PART VI ─────────────────────────────────────────────────────────────────
  {
    number: 25,
    slug: "chapter-25",
    part: "VI",
    partTitle: "The Food System",
    title: "EatoSystem — The Food System",
    description: "The complete picture. How everything connects into one unified approach to food, health, family life, and living well — and where EatoBiotics fits within the broader EatoSystem vision.",
    status: "coming-soon",
    readingTime: 45,
  },
]
