import type { Chapter } from "./chapters"
import { PART_COLORS } from "./chapters"

export { PART_COLORS }

export const chaptersMind: Chapter[] = [
  // ── PART I ──────────────────────────────────────────────────────────────────
  {
    number: 1,
    slug: "chapter-1",
    part: "I",
    partTitle: "The Mind-Body Food System",
    title: "The Food System Inside Your Mind",
    description: "The gut-brain connection and why mental wellbeing is biological, emotional, and environmental.",
    status: "coming-soon",
    readingTime: 25,
  },
  {
    number: 2,
    slug: "chapter-2",
    part: "I",
    partTitle: "The Mind-Body Food System",
    title: "Modern Life Disrupted the System",
    description: "Ultra-processed food, poor sleep, isolation, overstimulation, chronic stress, alcohol, and routine collapse.",
    status: "coming-soon",
    readingTime: 28,
  },
  {
    number: 3,
    slug: "chapter-3",
    part: "I",
    partTitle: "The Mind-Body Food System",
    title: "The Gut-Brain Biotics Framework",
    description: "How the microbiome, inflammation, blood sugar, and nervous system interact.",
    status: "coming-soon",
    readingTime: 30,
  },
  {
    number: 4,
    slug: "chapter-4",
    part: "I",
    partTitle: "The Mind-Body Food System",
    title: "The EatoBiotics Mind Method",
    description: "A supportive daily framework for steadiness, clarity, and resilience.",
    status: "coming-soon",
    readingTime: 26,
  },

  // ── PART II ─────────────────────────────────────────────────────────────────
  {
    number: 5,
    slug: "chapter-5",
    part: "II",
    partTitle: "Foods That Support the Mind",
    title: "Prebiotic Foods for Mental Wellbeing",
    description: "Feeding the microbiome that supports the gut-brain axis.",
    status: "coming-soon",
    readingTime: 38,
  },
  {
    number: 6,
    slug: "chapter-6",
    part: "II",
    partTitle: "Foods That Support the Mind",
    title: "Probiotic Foods and the Gut-Brain Connection",
    description: "What fermented foods may contribute to mood and digestive stability.",
    status: "coming-soon",
    readingTime: 40,
  },
  {
    number: 7,
    slug: "chapter-7",
    part: "II",
    partTitle: "Foods That Support the Mind",
    title: "Postbiotic Results and Brain Support",
    description: "Short-chain fatty acids, inflammation balance, gut lining, and signaling pathways.",
    status: "coming-soon",
    readingTime: 42,
  },
  {
    number: 8,
    slug: "chapter-8",
    part: "II",
    partTitle: "Foods That Support the Mind",
    title: "Polyphenols, Omega-3s, and Brain Protection",
    description: "Protective compounds that may support cognition and mood.",
    status: "coming-soon",
    readingTime: 45,
  },
  {
    number: 9,
    slug: "chapter-9",
    part: "II",
    partTitle: "Foods That Support the Mind",
    title: "Protein, Fats, and Blood Sugar Stability",
    description: "Why steady energy matters for emotional and mental steadiness.",
    status: "coming-soon",
    readingTime: 44,
  },

  // ── PART III ────────────────────────────────────────────────────────────────
  {
    number: 10,
    slug: "chapter-10",
    part: "III",
    partTitle: "The 5 Outcomes",
    title: "Calm",
    description: "Reducing chaos in the internal system.",
    status: "coming-soon",
    readingTime: 40,
  },
  {
    number: 11,
    slug: "chapter-11",
    part: "III",
    partTitle: "The 5 Outcomes",
    title: "Clarity",
    description: "Focus, mental sharpness, and reduced brain fog.",
    status: "coming-soon",
    readingTime: 44,
  },
  {
    number: 12,
    slug: "chapter-12",
    part: "III",
    partTitle: "The 5 Outcomes",
    title: "Mood Stability",
    description: "Supporting steadier emotional patterns.",
    status: "coming-soon",
    readingTime: 48,
  },
  {
    number: 13,
    slug: "chapter-13",
    part: "III",
    partTitle: "The 5 Outcomes",
    title: "Stress Resilience",
    description: "Helping the body recover from daily load.",
    status: "coming-soon",
    readingTime: 50,
  },
  {
    number: 14,
    slug: "chapter-14",
    part: "III",
    partTitle: "The 5 Outcomes",
    title: "Recovery",
    description: "Sleep, repair, nervous system regulation, and rebuilding capacity.",
    status: "coming-soon",
    readingTime: 52,
  },

  // ── PART IV ─────────────────────────────────────────────────────────────────
  {
    number: 15,
    slug: "chapter-15",
    part: "IV",
    partTitle: "The Practical Support System",
    title: "The Mind-Supportive Kitchen",
    description: "Foods, tools, routines, and environmental design.",
    status: "coming-soon",
    readingTime: 54,
  },
  {
    number: 16,
    slug: "chapter-16",
    part: "IV",
    partTitle: "The Practical Support System",
    title: "The Mind Plate",
    description: "A meal framework built for stability and consistency.",
    status: "coming-soon",
    readingTime: 56,
  },
  {
    number: 17,
    slug: "chapter-17",
    part: "IV",
    partTitle: "The Practical Support System",
    title: "The 7-Day Nervous System Reset",
    description: "Simple food and habit support during difficult periods.",
    status: "coming-soon",
    readingTime: 50,
  },
  {
    number: 18,
    slug: "chapter-18",
    part: "IV",
    partTitle: "The Practical Support System",
    title: "The 21-Day Stability Build",
    description: "A deeper rhythm for food, sleep, movement, and recovery.",
    status: "coming-soon",
    readingTime: 55,
  },
  {
    number: 19,
    slug: "chapter-19",
    part: "IV",
    partTitle: "The Practical Support System",
    title: "The Mind Support Index",
    description: "A way to rank foods and habits by steadiness, nourishment, tolerance, and accessibility.",
    status: "coming-soon",
    readingTime: 48,
  },

  // ── PART V ──────────────────────────────────────────────────────────────────
  {
    number: 20,
    slug: "chapter-20",
    part: "V",
    partTitle: "Real Life + Support",
    title: "Low Periods, High Stress, and Difficult Weeks",
    description: "How to simplify the system when capacity is low.",
    status: "coming-soon",
    readingTime: 52,
  },
  {
    number: 21,
    slug: "chapter-21",
    part: "V",
    partTitle: "Real Life + Support",
    title: "When Someone You Love Is Struggling",
    description: "How family members can support without controlling or overwhelming.",
    status: "coming-soon",
    readingTime: 48,
  },
  {
    number: 22,
    slug: "chapter-22",
    part: "V",
    partTitle: "Real Life + Support",
    title: "Routine When Motivation Is Low",
    description: "Tiny actions, default meals, and non-perfection approaches.",
    status: "coming-soon",
    readingTime: 44,
  },
  {
    number: 23,
    slug: "chapter-23",
    part: "V",
    partTitle: "Real Life + Support",
    title: "Movement, Sunlight, and Nature",
    description: "Walking, gym, sea swimming, and environmental support for mental wellbeing.",
    status: "coming-soon",
    readingTime: 42,
  },
  {
    number: 24,
    slug: "chapter-24",
    part: "V",
    partTitle: "Real Life + Support",
    title: "Restore & Ritual — Breathwork, Meditation, Cold Exposure, and Supplements",
    description: "Supportive practices for recovery and regulation, used carefully and realistically.",
    status: "coming-soon",
    readingTime: 46,
  },

  // ── PART VI ─────────────────────────────────────────────────────────────────
  {
    number: 25,
    slug: "chapter-25",
    part: "VI",
    partTitle: "The Food System",
    title: "EatoSystem — The Food System",
    description: "The complete picture. How everything connects into one unified approach to food, health, mental wellbeing, and living well — and where EatoBiotics fits within the broader EatoSystem vision.",
    status: "coming-soon",
    readingTime: 45,
  },
]
