import { describe, it, expect } from "vitest"

import { ADDON_KEYS, type AddonType } from "@/lib/addon-types"
import { buildAddonLens, ADDON_SAFETY } from "@/lib/report/addon-lens"
import { ADDON_QUESTIONS } from "@/lib/assessment/addon-questions"
import { buildFoodSystemReport } from "@/lib/report/build-food-system-report"
import { foodSystemReportSchema } from "@/lib/report/food-system-report-types"
import { computeOverall, getProfile } from "@/lib/assessment-scoring"
import { CLAIMS, DENIAL_BOILERPLATE } from "./helpers/marketing-language"

/**
 * The deterministic lens chapter.
 *
 * Two properties matter most and are easy to lose:
 *   1. the lens must never touch the core Feed/Seed/Heal scores, and
 *   2. the four lenses must be genuinely different chapters, not one template
 *      with the noun swapped.
 */

type Sub = { prebiotics: number; probiotics: number; postbiotics: number }

const SCORES: Record<string, Sub> = {
  probioticsWeak: { prebiotics: 85, probiotics: 20, postbiotics: 85 },
  prebioticsWeak: { prebiotics: 25, probiotics: 80, postbiotics: 75 },
  postbioticsWeak: { prebiotics: 80, probiotics: 75, postbiotics: 22 },
}

function coreFor(sub: Sub) {
  const overall = computeOverall(sub)
  return buildFoodSystemReport({
    mode: "combined",
    subScores: sub,
    overall,
    profile: getProfile(overall, sub),
  })
}

/** Contrasting answer pairs per lens: A and B differ on every branch point. */
const ANSWERS: Record<AddonType, { a: Record<string, unknown>; b: Record<string, unknown> }> = {
  stability: {
    a: { lens1: "predictable", lens2: "none", lens3: ["veg-variety", "fermented"], lens4: "daily" },
    b: { lens1: "unpredictable", lens2: "stress-linked", lens3: ["none"], lens4: "rarely" },
  },
  glucose: {
    a: { lens1: "steady", lens2: "protein-led", lens3: "no-pattern", lens4: ["veg", "protein", "fats"] },
    b: { lens1: "lift-then-dip", lens2: "skipped", lens3: "mid-afternoon", lens4: ["alone"] },
  },
  mind: {
    a: { lens1: "steady", lens2: "no-pattern", lens3: ["fermented", "oily-fish"], lens4: "rarely" },
    b: { lens1: "skipped", lens2: "early-afternoon", lens3: ["none"], lens4: "daily" },
  },
  performance: {
    a: { lens1: "both", lens2: "recovered", lens3: ["protein", "colour", "slow-carbs"], lens4: "daily" },
    b: { lens1: "neither", lens2: "depleted", lens3: ["variable"], lens4: "rarely" },
  },
}

function lensFor(addon: AddonType, which: "a" | "b" = "a", sub = SCORES.probioticsWeak, isFamily = false) {
  return buildAddonLens({ addon, answers: ANSWERS[addon][which], foodSystem: coreFor(sub), isFamily })
}

/**
 * Every branch of every lens, in both voices.
 *
 * Two hand-picked answer sets are not enough, and that was found the hard way:
 * a deliberately reintroduced grammar bug passed the guard because neither
 * fixture selected the answer option that reaches the broken line. Whole
 * paragraphs of copy were never generated by any test.
 *
 * This walks each question's option values one at a time, holding the others at
 * the "a" fixture, so every conditional branch in every builder produces text
 * that the grammar and CLAIMS guards then read.
 */
function everyBranchLens(): Array<readonly [string, ReturnType<typeof buildAddonLens>]> {
  const out: Array<readonly [string, ReturnType<typeof buildAddonLens>]> = []

  for (const addon of ADDON_KEYS) {
    for (const spec of ADDON_QUESTIONS[addon]) {
      const values = (spec.options ?? []).map((o) => o.value)
      for (const value of values) {
        for (const isFamily of [false, true]) {
          const answers = {
            ...ANSWERS[addon].a,
            // multi questions take an array, single/yesno a string
            [spec.id]: spec.type === "multi" ? [value] : value,
          }
          out.push([
            `${addon}/${spec.id}=${value}/${isFamily ? "family" : "you"}`,
            buildAddonLens({ addon, answers, foodSystem: coreFor(SCORES.probioticsWeak), isFamily }),
          ] as const)
        }
      }
    }
  }
  return out
}

describe("the lens never touches the core scores", () => {
  it.each(ADDON_KEYS)("%s leaves bioticScores and the ranking identical", (addon) => {
    const before = coreFor(SCORES.probioticsWeak)
    const snapshot = JSON.stringify({ s: before.bioticScores, k: before.systemSnapshot })

    buildAddonLens({ addon, answers: ANSWERS[addon].a, foodSystem: before })

    expect(JSON.stringify({ s: before.bioticScores, k: before.systemSnapshot })).toBe(snapshot)
  })

  it("identical core answers with different add-ons keep identical core scores", () => {
    const cores = ADDON_KEYS.map((addon) => {
      const core = coreFor(SCORES.probioticsWeak)
      buildAddonLens({ addon, answers: ANSWERS[addon].a, foodSystem: core })
      return JSON.stringify(core.bioticScores) + "|" + core.systemSnapshot.priorityPathway
    })
    expect(new Set(cores).size).toBe(1)
  })

  it("carries no invented score of its own", () => {
    for (const addon of ADDON_KEYS) {
      const lens = lensFor(addon)
      const blob = JSON.stringify(lens)
      // No "<Lens> Score", no "NN/100" claim inside the lens.
      expect(blob, addon).not.toMatch(/\b\d{1,3}\s*\/\s*100\b/)
      expect(blob.toLowerCase(), addon).not.toMatch(/your (stability|glucose|mind|performance) score/)
      expect(lens).not.toHaveProperty("score")
    }
  })
})

describe("the priority connection is derived from the core report", () => {
  it.each(ADDON_KEYS)("%s names the core's priority pathway, whatever the answers", (addon) => {
    for (const sub of Object.values(SCORES)) {
      const core = coreFor(sub)
      const lens = buildAddonLens({ addon, answers: ANSWERS[addon].b, foodSystem: core })
      expect(lens.priorityConnection.pathway).toBe(core.systemSnapshot.priorityPathway)
    }
  })

  it("the same lens changes its priority copy when the weak pathway changes", () => {
    for (const addon of ADDON_KEYS) {
      const whys = Object.values(SCORES).map(
        (sub) => buildAddonLens({ addon, answers: ANSWERS[addon].a, foodSystem: coreFor(sub) }).priorityConnection.why,
      )
      expect(new Set(whys).size, addon).toBe(3)
    }
  })
})

describe("contrasting answers produce materially different content", () => {
  it.each(ADDON_KEYS)("%s differs on summary, signals and loop actions", (addon) => {
    const a = lensFor(addon, "a")
    const b = lensFor(addon, "b")

    expect(a.patternSummary).not.toBe(b.patternSummary)
    expect(JSON.stringify(a.signals)).not.toBe(JSON.stringify(b.signals))
    expect(JSON.stringify(a.loopAdditions)).not.toBe(JSON.stringify(b.loopAdditions))

    // …while the fixed parts stay fixed.
    expect(a.safetyNote).toBe(b.safetyNote)
    expect(a.name).toBe(b.name)
    expect(JSON.stringify(a.evidenceNotes)).toBe(JSON.stringify(b.evidenceNotes))
  })
})

describe("the four lenses are not renamed templates", () => {
  const lenses = ADDON_KEYS.map((a) => lensFor(a))

  it("every lens has a distinct name, examines line and safety note", () => {
    for (const field of ["name", "shortLabel", "examines", "safetyNote"] as const) {
      const values = lenses.map((l) => l[field])
      expect(new Set(values).size, field).toBe(ADDON_KEYS.length)
    }
  })

  it("pattern summaries are distinct across lenses on identical scores", () => {
    expect(new Set(lenses.map((l) => l.patternSummary)).size).toBe(ADDON_KEYS.length)
  })

  it("pathway explanations are written in each lens's own terms", () => {
    for (const p of ["prebiotics", "probiotics", "postbiotics"] as const) {
      const copy = lenses.map((l) => l.pathwayConnections.find((c) => c.pathway === p)!.connection)
      expect(new Set(copy).size, p).toBe(ADDON_KEYS.length)
    }
  })

  it("loop actions are distinct across lenses", () => {
    const joined = lenses.map((l) => l.loopAdditions.map((x) => x.action).join("|"))
    expect(new Set(joined).size).toBe(ADDON_KEYS.length)
  })

  it("evidence differs between lenses rather than one shared list", () => {
    const urls = lenses.map((l) => l.evidenceNotes.map((e) => e.sourceUrl).sort().join("|"))
    expect(new Set(urls).size).toBe(ADDON_KEYS.length)
  })

  /**
   * The blunt template check: strip the lens's own nouns out and the chapters
   * should STILL differ. A renamed template would collapse to one string here.
   */
  it("chapters differ by more than their own name", () => {
    const NOUNS = /stability|glucose|mind|performance|digestion|digestive|energy|craving|focus|recovery|activity/gi
    const skeletons = lenses.map((l) =>
      [l.patternSummary, ...l.loopAdditions.map((x) => x.action), ...l.signals.map((s) => s.whatToNotice)]
        .join(" ")
        .replace(NOUNS, "•"),
    )
    expect(new Set(skeletons).size).toBe(ADDON_KEYS.length)
  })
})

describe("family wording", () => {
  it.each(ADDON_KEYS)("%s reads as a household when the foundation is Family", (addon) => {
    const you = lensFor(addon, "a", SCORES.probioticsWeak, false)
    const family = lensFor(addon, "a", SCORES.probioticsWeak, true)

    expect(family.patternSummary).not.toBe(you.patternSummary)
    expect(family.patternSummary).toMatch(/household/i)
    expect(you.patternSummary).not.toMatch(/household/i)
  })
})

/**
 * Grammar guard.
 *
 * The voice helper originally passed one string, `"you are"` / `"the household
 * is"`, into every slot that needed a subject or a possessive. Three of its
 * four uses came out broken — "something you are tracked closely yet", "most
 * within you are control" — and every other test passed, because they all
 * checked that strings DIFFER, not that they read as English. This checks the
 * shapes that mis-substitution produces, in both voices.
 */
describe("both voices read as English", () => {
  const BROKEN = [
    /\byou are (tracked|watched|noticed|seen)\b/i,
    /\bthe household is (tracked|watched|noticed|seen)\b/i,
    /\bwithin (you are|the household is)\b/i,
    /\b(you are|the household is) control\b/i,
    /\byour (are|is|has|have)\b/i,
    /\bthe household's (are|is|has|have)\b/i,
    /\bYour household's answers describe your\b/i,
  ]

  it.each(everyBranchLens())("%s contains no mis-substituted voice", (_label, lens) => {
    const text = [
      lens.patternSummary,
      lens.priorityConnection.why,
      ...lens.signals.map((s) => s.whatToNotice),
      ...lens.loopAdditions.map((l) => l.action),
      ...lens.pathwayConnections.map((p) => p.connection),
    ].join("\n")

    for (const bad of BROKEN) {
      const m = text.match(bad)
      expect(m?.[0], `"${m?.[0]}" in:\n${text}`).toBeUndefined()
    }
  })

  it("the grammar guard is not vacuous", () => {
    expect(BROKEN.some((r) => r.test("something you are tracked closely yet"))).toBe(true)
    expect(BROKEN.some((r) => r.test("most within you are control"))).toBe(true)
  })
})

describe("hollow lenses do not validate", () => {
  const base = coreFor(SCORES.probioticsWeak)

  function withLens(lens: unknown) {
    return foodSystemReportSchema.safeParse({ ...base, lens })
  }

  it("a fully built lens validates", () => {
    expect(withLens(lensFor("mind")).success).toBe(true)
  })

  it("a report with no lens still validates", () => {
    expect(foodSystemReportSchema.safeParse(base).success).toBe(true)
  })

  it.each([
    ["empty strings", { ...lensFor("mind"), patternSummary: "", examines: "" }],
    ["no signals", { ...lensFor("mind"), signals: [] }],
    ["no loop actions", { ...lensFor("mind"), loopAdditions: [] }],
    ["no evidence", { ...lensFor("mind"), evidenceNotes: [] }],
    ["blank safety note", { ...lensFor("mind"), safetyNote: "" }],
    ["unknown key", { ...lensFor("mind"), key: "recovery" }],
    ["out-of-range week", { ...lensFor("mind"), loopAdditions: [{ week: 9, action: "x".repeat(30) }, { week: 1, action: "y".repeat(30) }] }],
  ])("rejects a lens with %s", (_label, lens) => {
    expect(withLens(lens).success).toBe(false)
  })
})

describe("safety wording is fixed and lens-appropriate", () => {
  it("glucose states that it does not measure blood glucose", () => {
    expect(ADDON_SAFETY.glucose.toLowerCase()).toContain("does not measure blood glucose")
  })

  it("mind does not diagnose, treat, or claim change", () => {
    const s = ADDON_SAFETY.mind.toLowerCase()
    expect(s).toContain("does not diagnose")
    expect(s).toMatch(/makes no claim/)
    expect(s).toMatch(/anxiety|low mood/)
  })

  it("stability and performance avoid guarantees and deadlines", () => {
    for (const key of ["stability", "performance"] as const) {
      const s = ADDON_SAFETY[key].toLowerCase()
      expect(s, key).not.toMatch(/guarantee|will improve|within \d+ (days|weeks)/)
    }
    expect(ADDON_SAFETY.performance.toLowerCase()).toContain("no result by any particular date")
  })

  it("every lens carries its own safety note verbatim", () => {
    for (const addon of ADDON_KEYS) {
      expect(lensFor(addon).safetyNote).toBe(ADDON_SAFETY[addon])
    }
  })
})

describe("evidence notes are real and well formed", () => {
  it.each(ADDON_KEYS)("%s cites at least two resolvable-looking sources", (addon) => {
    const notes = lensFor(addon).evidenceNotes
    expect(notes.length).toBeGreaterThanOrEqual(2)
    for (const n of notes) {
      expect(n.claim.length).toBeGreaterThan(40)
      expect(n.sourceTitle.length).toBeGreaterThan(10)
      expect(n.sourceUrl).toMatch(/^https:\/\/(www\.)?(who\.int|nhs\.uk|nccih\.nih\.gov|pubmed\.ncbi\.nlm\.nih\.gov)\//)
    }
  })
})

/**
 * The real corpus rules, over the generated lens content — the same harness
 * fallback-report-claims.test.ts uses, for the same reason: a regex over the
 * source file would miss a claim assembled from two template fragments.
 */
describe("the real CLAIMS rules pass over every fallback lens", () => {
  it("has rules to run", () => {
    expect(CLAIMS.length).toBeGreaterThan(15)
  })

  it.each(everyBranchLens())("%s — no health-claim rule fires", (_label, lens) => {
    const text = JSON.stringify(lens).replace(DENIAL_BOILERPLATE, " ")
    expect(text.length).toBeGreaterThan(1_500)

    const hits: string[] = []
    for (const [rule, pattern] of CLAIMS) {
      const m = text.match(pattern)
      if (m) hits.push(`${rule}: "${m[0]}"`)
    }
    expect(hits, hits.join("\n")).toEqual([])
  })
})
